<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Lyrics Yo!</title>
    <meta name="description" content=" "/>
    <meta name="keywords" content=""/>           
    <meta name="author" content="@frasiocht"> 
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=1"/>
    <meta name="format-detection" content="telephone=no">    
    <link rel='stylesheet' href='/css/global.css' />
    <link rel='stylesheet' href='css/highlighter.css'/>
    <script src='/js/jquery.js'></script>       
    <script type="text/javascript">
	  // unblock when ajax activity stops 
      //$(document).ajaxStop($.unblockUI);
    </script>
</head>
<body  ontouchstart="">
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=487960967905539";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div id="header" class="header">
    <div id="headerButtonsWrapper" style="max-width:900px; margin-left:auto; margin-right:auto;">
        <a href="/">
            <div id="marvelIcon" class="" style="display:inline-block; padding-right:5em;">
                <span class="txt_lyricsyo" style="line-height:63px; padding-left:5px;">LyricsYo</span>
            </div>
        </a>
    </div>
</div>  
    <?php echo $this->layout()->content; ?>
    <div style="height:4em;"></div>

<div id="footer" style="max-width:900px; margin-left:auto; margin-right:auto; margin-bottom:5em; line-height: 35px;">
    <div id="socialHolder" style="margin-left:5px; float:left; display: inline-block; line-height:35px;">
        <div id="facebookHolder" class="socialHolder" style="width:6em;">
            <div class="fb-like" data-href="http://lyricsyo.whether.me" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false"></div>
        </div>
        <div id="twitterHolder" class="socialHolder" style="width:5.5em;">
            <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://lyricsyo.whether.me" data-via="frasiocht">Tweet</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        </div>
        <div id="googleHolder" class="socialHolder">
            <!-- Place this tag where you want the share button to render. -->
            <div class="g-plus" data-action="share" data-annotation="none" data-height="15"></div>

            <!-- Place this tag after the last share tag. -->
            <script type="text/javascript">
            (function() {
                var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                po.src = 'https://apis.google.com/js/plusone.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
            })();
            </script>
        </div>     
    </div>
    <div style="margin-left:5px; float:right; display: inline-block; ">
        <img src="/images/logos.png"/>
    </div>
</div>
</body>