<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Marvel</title>
    <meta name="description" content=" "/>
    <meta name="keywords" content=""/>           
    <meta name="author" content="@frasiocht"> 
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=1"/>
    <meta name="format-detection" content="telephone=no">
    <script type="text/javascript" src="http://www.google.com/jsapi"></script>
    <link rel='stylesheet' href='/css/global.css' />    
    <script src='/js/jquery.js'></script>    
    <script src="/js/blockui.js"></script>            
    <script src="/js/jquery.gritter.js"></script>
    <script src="/js/utils.js"></script>
    <link rel='stylesheet' href='/css/jquery.gritter.css'/>   
    <link rel='stylesheet' href='/css/filedrop.css'/>     
    <script type="text/javascript">
	  // unblock when ajax activity stops 
      //$(document).ajaxStop($.unblockUI);
    </script>
</head>
<body  ontouchstart="">
    <?php echo $this->layout()->content; ?>
</body>